services:
  - type: web
    name: gyaru-album-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HOST_URL
        sync: false
